blending/urls.py
from django.urls import path
from  . import views

urlpatterns =[
    path('coalstock/',views.coalspec_list, name = 'coalstockforblending'),
    path('blending/',views.calculate_blending, name = 'calculateblending'),
    path('blending/history',views.search_history, name= 'searchhistory'),
    path('blending/resumehistory',views.search_resume_history, name= 'searchresumehistory'),
    path('note/',views.create_note, name = 'createnote'),

    path('blending/prep',views.prepare_for_blend, name = 'prepareblending'),


]

coaljson/urls.py
from django.urls import path
from  . import views
from .views import SelectCoalView
from django.contrib.auth import views as authview
from .forms import UserLoginForm
urlpatterns =[
    path('coal/',views.new_coal, name='new_coal'),
    path('coaljson/',views.new_coal_json, name='new_coal_json'),
    path('coalspec/', views.new_coal_spec,name='coalspeccreate'),
    path('coalspeclist/',views.coalspec_list, name='coalspeclist'),
    path('coalspeclistapi/', views.coalspecserializer_list, name ='coalspecapi'),
    # path('',authview.LoginView.as_view(
    #         template_name="login.html",
    #         authentication_form=UserLoginForm
    #         ),
    #     name='login'),

    path('',views.index, name = 'index'),
    path('coalstock/', views.new_coal_stock_unit, name='new_coal_stock'),
    path('coalstock/<unit>/listcsu', views.coal_stock_unit_list, name='coal_stock_unit_list'),
    path('coalstock/search', views.search_stock_unit, name='search_coal_stock_unit'),
    path('coalstock/search_old', views.search_stock_unit_old, name='search_coal_stock_unit_old'),
    path('coalstock/search_op', views.search_stock_unit_short, name='search_coal_stock_unit_short'),

    path('coalstock/<id>/updateunit', views.update_coal_stock_unit, name='updatecoalstock'),
    path('coalstock/<id>/updatesimple', views.update_stock_simple, name='simpleupdatecoal'),
    path('coalstock/<id>/update', views.update_stock_simple2, name='simpleupdatecoal2'),
    path('coalstock/delete/<id>', views.delete_coal_stock_unit, name='deletecoalstock'),
    path('coalstock/fromapi', views.coalstockfromapi, name='getcoalstockfromapi'),
    #path('coalstock/prep/', views.get_coal_for_blending, name='preparecoalforblending'),
    path('coalstock/prep/', views.get_coal_for_blending_op, name='preparecoalforblending'),
    path('coalstock/<unit>/list', views.view_coal_stock_unit, name='coal_stock_unit'),
    path('coalstock/temp/', views.generatebiofromtemp, name='generate_bio_from_temp'),

    path('coalstock/fromspecapi', views.get_coal_from_db, name='getcoalstockfromspecapi'),

    path('coalstock/bio', views.get_bio_for_blending, name='getbioforblend'),
    path('coalstock/bio/<int:bio_id>', views.select_bio_for_blending, name='selectbioforblend'),
    path('coalstock/tkg', views.get_coal_tk_for_blending, name='gettongkang'),
    path('coalstock/tk/<int:coaltk_id>', views.select_coal_tk_for_blending, name='selecttongkang'),
    path('coalstock/cyd', views.get_coal_cyrd_for_blending, name='getcoalyard'),
    path('coalstock/cyd/<int:cyrd_id>', views.get_coal_cyrd_for_blending, name='selectcoalyards'),
    path('coalstock/next', views.nextstep_setunit, name='nextstepsetunit'),
    path('coalstock/cyd/<int:cyrd_id>', views.submit_coal_for_blending, name='submitcoalforblend'),
    path('coalstock/select/<int:pk>', SelectCoalView.as_view(), name="selectcoal")








]

restfulapicrud/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('setparam/', include(('setparam.urls', 'setparam'), namespace='setparam')),
    path('blending/', include(('blending.urls', 'blending'), namespace='blending')),
    path('optbeban/', include(('optpembebanan.urls', 'optbeban'), namespace='optbeban')),
    path('',include(('coaljson.urls','coaljson'),namespace='coaljson')),
    #path('',include('crudbasic.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),


]

coaljson/models.py
from django.db import models
from setparam.models import UnitBoiler
import datetime

class Coal(models.Model):
    """
    {
   "Pemasok": "Bukit Asam",
   "Kalori": 4732,
   "TM": 29.19,
   "TS": 0.36,
   "ASH": 5.76,
   "IDTReducing": 1270,
   "SiO2": 57.96,
   "Al2O3": 26.85,
   "Fe2O3": 5.19,
   "CaO": 3.24,
   "MgO": 1.43,
   "Na2O": 1.2,
   "K2O": 0.59,
   "TiO2": 1.02,
   "SO3": 1.95,
   "HTmax": 1400,
   "JenisAbu": "Bituminous",
   "SI": 2268.8,
   "Slagging": "Low",
   "C": 61.28,
   "H": 4.02,
   "N": 0.92,
   "O": 13.29
 },
    """
    KATEGORI_BB = (
        ('BB', 'Batubara'),
        ('BIO', 'Biomass'),
    )

    pemasok = models.CharField(max_length=100, default='not specified')
    kategori_bhn_baku = models.CharField(max_length=3, choices=KATEGORI_BB, default='BB')
    kategori = models.CharField(max_length=13, default='not specified')
    kalori = models.IntegerField()
    tm = models.FloatField()
    ts = models.FloatField()
    ash = models.FloatField()
    idtreducing = models.IntegerField()
    sio2 = models.FloatField()
    al2o3 = models.FloatField()
    fe2o3 = models.FloatField()
    cao = models.FloatField()
    mgo = models.FloatField()
    na2o = models.FloatField()
    k2o = models.FloatField()
    tio2 = models.FloatField()
    so3 = models.FloatField()
    htmax = models.IntegerField()
    jenisabu = models.CharField(max_length=20, default='not specified')
    si = models.FloatField()
    slagging = models.CharField(max_length=10, default='not specified')
    c = models.FloatField()
    h = models.FloatField()
    n = models.FloatField()
    o = models.FloatField()
    tanggal = models.DateField(null=True) #asumsi jika untuk coalyard adalah data coalyard
#bisa dinormalisasi kalau mau meningkatkan response time

class CoalForBlend(models.Model):
    unit = models.ForeignKey(UnitBoiler, on_delete=models.CASCADE)
    tanggal = models.DateField(null=True)
    waktu = models.TimeField()
    coal = models.ForeignKey(Coal, on_delete = models.CASCADE)

class CoalJSON(models.Model):
    data = models.JSONField(default=None)

class CoalSpec(models.Model):
    coalspecdata = models.TextField()

class CoalStockUnit(models.Model):
    KATEGORI_STOK=(
        ('T','Tongkang'),
        ('C','Coal Yard'),
    )
    KATEGORI_BB=(
        ('BB','Batubara'),
        ('BIO','Biomass'),
    )

    unit = models.ForeignKey(UnitBoiler, on_delete=models.CASCADE)
    tanggal = models.DateField(auto_now_add=False,blank=True, auto_now=False,default=datetime.date.today())
    timestamp = models.DateField(auto_now_add=True,auto_now=False)
    kategori_stock = models.CharField(max_length=2,choices=KATEGORI_STOK )
    kategori_bhn_baku= models.CharField(max_length=3, choices=KATEGORI_BB)
    coalstock = models.TextField(max_length=550)

    def __str__(self):
        return f'1 item of coal stock at {self.tanggal}'

coaljson/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect,reverse
from .forms import CoalDataJSONForm, CoalForm,CoalSpecForm, CoalStockUnitForm, \
                    CoalStockSimpleForm, SearchStockByUnitForm,SetURLAddressForm, CoalStockManualSettingForm, CoalForBlendForm
from blending.forms import PrepareBlandForm
from .models import CoalJSON,CoalSpec, CoalStockUnit, Coal, CoalForBlend

from .serializers import CoalSpecSerializers
from setparam.models import UnitBoiler, RohUnit
import datetime
import  requests
import json
from django.views import View
from django.views.generic.edit import FormView
from django.contrib.auth.forms import AuthenticationForm
import random
from django.core import serializers

#https://studygyaan.com/django/how-to-execute-crud-using-django-ajax-and-json
class CoalForBlendView(FormView):
    template_name = 'coalstock/setbiomass.html'
    form_class = CoalForBlendForm

    def form_valid(self, form):
        coalforblend = CoalForBlend.objects.update_or_create(
            unit = form.cleaned_data["unit"],
            tanggal = form.cleaned_data["tanggal"],
            waktu = form.cleaned_data["waktu"]
        )
    def post(self,request,pk,*args,**kwargs):
        if request.is_ajax():
            coal = Coal.objects.get(pk = pk)
            # edit data coal for blending


class SelectCoalView(View):
    form_class = CoalForBlendForm
    coals = []

    def post(self,request, pk, *args, **kwargs):
        coals =[]
        if request.is_ajax():
            form = self.form_class(request.POST)
            if form.is_valid():
                unit = form.cleaned_data["unit"]
                tanggal = form.cleaned_data["tanggal"]
                waktu = form.cleaned_data["waktu"]
                #data coal yng dipilih harus dikirim sebagai json untuk disimpan kedalam database
                return JsonResponse({"message":"success", "coals":coals})
        return JsonResponse({"message": "Wrong request"})

    def get(self, request, pk, *args, **kwargs):
        if request.is_ajax():
            coal = Coal.objects.get(pk=pk)
            if coal:
                self.coals.append(coal)
                array_result = serializers.serialize('json', [coal], ensure_ascii=False)
                coal_in_json = array_result[1:-1]
                return JsonResponse({"message": "success", "coals": coal_in_json})
        return JsonResponse({"message": "Wrong request"})


def add_bio_to_db_coal(request):
    item1 = {
        "Pemasok": "Arta Daya Coalindo",
        "Kategori": "biomassa",
        "Kalori": 3300,
        "TM": 59.35,
        "TS": 0,
        "ASH": 0,
        'IDTReducing': 0,
        'SiO2': 0,
        'Al2O3': 0,
        'Fe2O3': 0,
        'CaO': 0,
        'MgO': 0,
        'Na2O': 0,
        'K2O': 0,
        'TiO2': 0,
        'SO3': 0,
        'HTmax': 0,
        'JenisAbu': 0,
        'SI': 0,
        'Slagging': 0,
        'C': 0,
        'H': 0,
        'N': 0,
        'O': 0
    }
    item2 = {
        "Pemasok": "Arta Daya Coalindo",
        "Kategori": "biomassa",
        "Kalori": 2300,
        "TM": 59.35,
        "TS": 0,
        "ASH": 0,
        'IDTReducing': 0,
        'SiO2': 0,
        'Al2O3': 0,
        'Fe2O3': 0,
        'CaO': 0,
        'MgO': 0,
        'Na2O': 0,
        'K2O': 0,
        'TiO2': 0,
        'SO3': 0,
        'HTmax': 0,
        'JenisAbu': 0,
        'SI': 0,
        'Slagging': 0,
        'C': 0,
        'H': 0,
        'N': 0,
        'O': 0
    }
    items = [item1,item2]
    for item in items:
        bio = Coal.objects.create(pemasok=item['Pemasok'],
                              kategori_bhn_baku='BIO',
                              kategori=item['Kategori'],
                              kalori=item['Kalori'],
                              tm=item['TM'],
                              ts=item['TS'],
                              ash=item['ASH'],
                              idtreducing=item['IDTReducing'],
                              sio2=item['SiO2'],
                              al2o3=item['Al2O3'],
                              fe2o3=item['Fe2O3'],
                              cao=item['CaO'],
                              mgo=item['MgO'],
                              na2o=item['Na2O'],
                              k2o=item['K2O'],
                              tio2=item['TiO2'],
                              so3=item['SO3'],
                              htmax=item['HTmax'],
                              jenisabu=item['JenisAbu'],
                              si=item['SI'],
                              slagging=item['Slagging'],
                              c=item['C'],
                              h=item['H'],
                              n=item['N'],
                              o=item['O'])

#data still not display at html file
def get_coal_from_db(request):
    #popuate database coal from api coalspec
    item = {
        "Pemasok": "Arta Daya Coalindo",
        "Kategori": "biomassa",
        "Kalori": 3300,
        "TM": 59.35,
        "TS": 0,
        "ASH": 0,
        'IDTReducing': 0,
        'SiO2': 0,
        'Al2O3': 0,
        'Fe2O3': 0,
        'CaO': 0,
        'MgO': 0,
        'Na2O': 0,
        'K2O': 0,
        'TiO2': 0,
        'SO3': 0,
        'HTmax': 0,
        'JenisAbu': 0,
        'SI': 0,
        'Slagging': 0,
        'C': 0,
        'H': 0,
        'N': 0,
        'O': 0
    }
    context = None
    coal_url = 'http://127.0.0.1:8005/api/coalspecstock/'
    try:
        coalresponse = requests.get(coal_url, timeout=5)
        if coalresponse is not None :
            coalstocks = []
            bio = Coal.objects.create(pemasok=item['Pemasok'],
                                      kategori_bhn_baku='BIO',
                                      kategori=item['Kategori'],
                                      kalori=item['Kalori'],
                                      tm=item['TM'],
                                      ts=item['TS'],
                                      ash=item['ASH'],
                                      idtreducing=item['IDTReducing'],
                                      sio2=item['SiO2'],
                                      al2o3=item['Al2O3'],
                                      fe2o3=item['Fe2O3'],
                                      cao=item['CaO'],
                                      mgo=item['MgO'],
                                      na2o=item['Na2O'],
                                      k2o=item['K2O'],
                                      tio2=item['TiO2'],
                                      so3=item['SO3'],
                                      htmax=item['HTmax'],
                                      jenisabu=item['JenisAbu'],
                                      si=item['SI'],
                                      slagging=item['Slagging'],
                                      c=item['C'],
                                      h=item['H'],
                                      n=item['N'],
                                      o=item['O'])
            coalstocks.append(bio)
            coalsjson = json.loads(coalresponse.text)
            for item in coalsjson:
                c = Coal.objects.create(pemasok=item['Pemasok'],
                                      kategori_bhn_baku='BB',
                                      kategori=item['Kategori'],
                                      kalori=item['Kalori'],
                                      tm=item['TM'],
                                      ts=item['TS'],
                                      ash=item['ASH'],
                                      idtreducing=item['IDTReducing'],
                                      sio2=item['SiO2'],
                                      al2o3=item['Al2O3'],
                                      fe2o3=item['Fe2O3'],
                                      cao=item['CaO'],
                                      mgo=item['MgO'],
                                      na2o=item['Na2O'],
                                      k2o=item['K2O'],
                                      tio2=item['TiO2'],
                                      so3=item['SO3'],
                                      htmax=item['HTmax'],
                                      jenisabu=item['JenisAbu'],
                                      si=item['SI'],
                                      slagging=item['Slagging'],
                                      c=item['C'],
                                      h=item['H'],
                                      n=item['N'],
                                      o=item['O'])

                coalstocks.append(c)

            context = {
                'coalstocks': coalstocks,

            }
            # return HttpResponseRedirect(reverse('coaljson:coal_stock_unit_list', args=(unit.id,)))
            return render(request, 'coaljson/preparecoalstock_view.html', context=context)
    except requests.exceptions.ConnectionError as e:
        pesan = "endpoint tidak tersedia"
        context = {
            'pesan': pesan,
        }
#get_coal_cyd_for_blending
# pilih beberapa dan update cookie dengan ajax
# kalau selesai maka lanjut ke proses penentuan unit dan waktu
def submit_coal_for_blending(request):
    #tampilkan form untuk memilih unit tanggal dan waktu

    pass
def nextstep_setunit(request):
    form = None
    if request.method =="POST":
        # ambil data coal dari session
        form = PrepareBlandForm(None)
        form.instance.created_by = request.user
        #selected_bio
        #selected_tkg
        #selected_cyrd
        selected_cyrds = []
        selected_bios = []
        selected_tkgs = []
        if 'selected_bio' in request.session and 'selected_tkg' in request.session and 'selected_cyrd'in request.session:
            selected_cyrds = Coal.objects.filter(pk__in=request.session['selected_cyrd'])

coaljson/templates/coaljson/coalstock.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    {{heading}}
{% endblock title %}
          {% block content %}




{% endblock }

coaljson/templates/coaljson/coalstockasli.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>coal stock</title>
</head>
<body>
<h1>Coal Stock</h1>
<table border="1">
    <thead>
    <tr>
        <th>Sumber Pasokan</th>
        <th>Pemasok</th>
        <th>Kategori</th>
        <th>Kalori</th>
        <th>Total Moisture</th>
        <th>Total Shulfur</th>
        <th>Total Ash</th>

    </tr>
    </thead>
    <tbody>
    {% for coal in coals %}
    <tr>
        <td>
            {{ coal.sumberpasokan }}<br>
        </td>
        <td>
            {{ coal.Pemasok }}<br>
        </td>
        <td>
            {{ coal.Kategori }}<br>
        </td>
        <td>
            {{coal.Kalori}}
        </td>
        <td>
            {{coal.TM}}
        </td>
        <td>
            {{coal.TS}}
        </td>
        <td>
            {{coal.ASH}}
        </td>


    </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>

coaljson/templates/coaljson/coalstockfromapi.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="alert alert-primary" role="alert">
    <h3>Ambil Stock Batubara</h3>
</div>
<form method="POST">
    {% csrf_token %}

    {% for data in form %}
    <div class="form-group">
        <label class="col-sm-2 col-form-label">{{data.label_tag}}</label>
        <div class="col-sm-12">
            {{data}}
        </div>
    </div>
    {% endfor %}
    <br>
    <div>
        <button type="submit" class="btn btn-primary ">Unduh</button>
    </div>

</form>

<div class="row g-3">
    <p></p>
</div>
<div class="alert alert-primary" role="alert">
    <h3>Stok Batubara</h3>
</div>
<table class="table table-bordered">
    <thead>
    <tr>
        <th scope="col">Tanggal</th>
        <th scope="col">Unit</th>
        <th scope="col">Spesifikasi</th>
        <th scope="col">Letak</th>
        <th scope="col">Jenis Bahan</th>
        <th scope="col">Aksi</th>
        <th scope="col">Aksi</th>
    </tr>
    </thead>
    <tbody>
    {% for coal in coalstocks %}
    <tr>
        <th scope="row">{{coal.tanggal}}</th>
        <td>{{coal.unit}}</td>
        <td>{{coal.coalstock}}</td>
        <td>{{coal.kategori_stock}}</td>
        <td>{{coal.kategori_bhn_baku}}</td>
        <td>
            <form method="post">
                {% csrf_token %}
                <a href="{% url 'coaljson:updatecoalstock' coal.id %}" class="btn btn-outline-success">Update</a>
            </form>
        </td>
        <td>
            <form method="post">
                {% csrf_token %}
                <a href="{% url 'coaljson:deletecoalstock' coal.id %}" class="btn btn-outline-warning" onsubmit="">Delete</a>
            </form>
        </td>

    </tr>
    {% endfor %}
    </tbody>
</table>



{% endblock %}

coaljson/templates/coaljson/coalstocklist.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    {{heading}}
{% endblock title %}

{% block content %}
<div class="alert alert-primary" role="alert">
    <h3>Pilih Unit Boiler</h3>
</div>

    <form method="post">
       {% csrf_token %}
       {% for data in form %}
    <div class="form-group">
        <label class="col-sm-2 col-form-label">{{data.label_tag}}</label>
        <div class="col-sm-12">
            {{data}}
        </div>
    </div>
    {% endfor %}
    <br>
    <button type="submit" class="btn btn-success">Pilih</button>
        <br>
    </form>
 
    {% if tampil is True %}

         <h1>Stok Batubara </h1>

        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Tanggal</th>
                <th scope="col">Unit</th>
              <th scope="col">Spesifikasi</th>
              <th scope="col">Letak</th>
              <th scope="col">Jenis Bahan</th>
               <th scope="col">Aksi</th>
                <th scope="col">Aksi</th>
            </tr>
          </thead>
          <tbody>
             {% for coal in stocks %}
            <tr>
              <th scope="row">{{coal.tanggal}}</th>
                <td>{{coal.unit}}</td>
              <td>{{coal.coalstock}}</td>
              <td>{{coal.kategori_stock}}</td>
              <td>{{coal.kategori_bhn_baku}}</td>
                <td>
                    <form method="post" >
                        {% csrf_token %}
                         <!--<a href="{% url 'coaljson:simpleupdatecoal' coal.id %}" class="btn btn-outline-success">Update</a>-->
                         <a href="{% url 'coaljson:updatecoalstock' coal.id %}" class="btn btn-outline-success">Update</a>
                    </form>
                </td>
                 <td>
                    <form method="post" >
                        {% csrf_token %}
                        <a href="{% url 'coaljson:deletecoalstock' coal.id %}" class="btn btn-outline-warning" onsubmit="">Delete</a>
                    </form>
                </td>

            </tr>
           {% endfor %}
          </tbody>
        </table>
    {% endif %}
    {% if tampil is False%}
        <h3>{{pesan}}</h3>
    {% endif %}
{% endblock %}

coaljson/templates/coaljson/coalstocklist_short.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    {{heading}}
{% endblock title %}

{% block content %}
<div class="alert alert-primary" role="alert">
    <h3>Pilih Unit Boiler</h3>
</div>

    <form method="post">
       {% csrf_token %}
       {% for data in form %}
    <div class="form-group">
        <label class="col-sm-2 col-form-label">{{data.label_tag}}</label>
        <div class="col-sm-12">
            {{data}}
        </div>
    </div>
    {% endfor %}
    <br>
    <button type="submit" class="btn btn-success">Pilih</button>
        <br>
    </form>

    {% if tampil is True %}

   <div class="alert alert-primary" role="alert">
    <h3>Stok Batubara</h3>
</div>
<table class="table table-bordered">
    <thead>
    <tr>
        <th scope="col">No ID</th>
        <th scope="col">Unit</th>
        <th scope="col">Tanggal</th>
        <th scope="col">Asal</th>
        <th scope="col">Pemasok</th>
        <!--<th scope="col">Kategori</th> -->
        <th scope="col">Kalori</th>
        <th scope="col">TM</th>
        <th scope="col">TS</th>
        <th scope="col">ASH</th>
        <th scope="col">aksi</th>

    </tr>
    </thead>
    <tbody>
    {% for coal in coals %}
    <tr>

        <th scope="row">{{coal.id}}</th>
        <td>{{coal.unit}}</td>
        <td>{{coal.tanggal}}</td>
        <td>{{coal.sumberpasokan}}</td>
        <td>{{coal.Pemasok}}</td>
        <!--<td>{{coal.Kategori}}</td>-->
        <td>{{coal.Kalori}}</td>
        <td>{{coal.TM}}</td>
        <td>{{coal.TS}}</td>
        <td>{{coal.ASH}}</td>
        <td>
            <form method="post">
                {% csrf_token %}
                <a href="{% url 'coaljson:simpleupdatecoal2' coal.id %}" class="btn btn-outline-success">Update</a>
            </form>
        </td>

    </tr>
    {% endfor %}
    </tbody>
</table>

    {% endif %}
    {% if tampil is False%}
        <h3>{{pesan}}</h3>
    {% endif %}
{% endblock %}

coaljson/templates/coaljson/confirm_deletecsu.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="alert alert-warning d-flex align-items-center" role="alert">
      <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
      <div>
        <h3>Are you sure you want to delete {{object}} ?"</h3>
      </div>
    </div>
    <form method="POST" action="{% url 'coaljson:deletecoalstock' object.id %}">
        {% csrf_token %}

        <input type="submit" value="Confirm" class="btn btn-warning">
        <a href= "{% url 'coaljson:coal_stock_unit_list' unit.id %}" class="btn btn-default"> Cancel </a>
    </form>

{% endblock content %}

coaljson/templates/coaljson/confirm_setunit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
     <div class="alert alert-warning d-flex align-items-center" role="alert">
      <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
      <div>
        <h3>Yakin semua batubara di coalyard sudah dipilih ?" ?"</h3>
      </div>
    </div>
    <form method="POST" action="{% url 'blending:prepareblending'  %}">
        {% csrf_token %}

        <input type="submit" value="Confirm" class="btn btn-warning">
        <a href= "{{ request.META.HTTP_REFERER }}" class="btn btn-default"> Cancel </a>
    </form>


{% endblock content %}

coaljson/templates/coaljson/preparecoalstock_view.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="alert alert-primary" role="alert">
    <h3>{{pesan}}</h3>
</div>


<div class="row g-3">
    <p></p>
</div>
<div class="alert alert-primary" role="alert">
    <h3>Stok Batubara</h3>
</div>
<table class="table table-bordered">
    <thead>
    <tr>
        <th scope="col">No ID</th>
        <th scope="col">Unit</th>
        <th scope="col">Tanggal</th>
        <th scope="col">Asal</th>
        <th scope="col">Pemasok</th>
        <th scope="col">Kategori</th>
        <th scope="col">Kalori</th>
        <th scope="col">TM</th>
        <th scope="col">TS</th>
        <th scope="col">ASH</th>
        <th scope="col">aksi</th>

    </tr>
    </thead>
    <tbody>
    {% for coal in coalstocks %}
    <tr>

        <th scope="row">{{coal.id}}</th>
        <td>{{coal.unit}}</td>
        <td>{{coal.tanggal}}</td>
        <td>{{coal.sumberpasokan}}</td>
        <td>{{coal.Pemasok}}</td>
        <td>{{coal.Kategori}}</td>
        <td>{{coal.Kalori}}</td>
        <td>{{coal.TM}}</td>
        <td>{{coal.TS}}</td>
        <td>{{coal.ASH}}</td>
        <td>
            <form method="post">
                {% csrf_token %}
                <a href="{% url 'coaljson:simpleupdatecoal2' coal.id %}" class="btn btn-outline-success">Update</a>
            </form>
        </td>

    </tr>
    {% endfor %}
    </tbody>
</table>


{% endblock %}