blending/urls.py
from django.urls import path
from  . import views

urlpatterns =[
    path('coalstock/',views.coalspec_list, name = 'coalstockforblending'),
    path('blending/',views.calculate_blending, name = 'calculateblending'),
    path('blending/history',views.search_history, name= 'searchhistory'),
    path('blending/resumehistory',views.search_resume_history, name= 'searchresumehistory'),
    path('note/',views.create_note, name = 'createnote'),

    path('blending/prep',views.prepare_for_blend, name = 'prepareblending'),


]

restfulapicrud/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('setparam/', include(('setparam.urls', 'setparam'), namespace='setparam')),
    path('blending/', include(('blending.urls', 'blending'), namespace='blending')),
    path('optbeban/', include(('optpembebanan.urls', 'optbeban'), namespace='optbeban')),
    path('',include(('coaljson.urls','coaljson'),namespace='coaljson')),
    #path('',include('crudbasic.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),


]

setparam/urls.py
from django.urls import path
from  . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns =[

    path ('ub/',views.create_ub,name ='createub'),
    path ('ub/<id>/view',views.view_unitboiler, name ='viewunit'),
    path ('ub/list',views.list_ub,name ='listunitboiler'),
    path('ub/<id>/updateub',views.update_unitboiler, name = 'updateunit'),
    path('ub/<id>/deleteub',views.delete_unitboiler, name = 'deleteunit'),

    path('roh/',views.set_rohunit_fromfile, name = 'setroh'),
    path('roh/template',views.roh_csv, name = 'rohtemplate'),

    path('hpbb/', views.createHargaPerkiraanBB, name ='createhpbb'),
    path('hpbb/<id>/deletehp', views.deleteHargaPerkiraanBB, name ='deletehpbb'),
    path('hpbb/<id>/edithp', views.editHargaPerkiraanBB, name ='edithpbb'),

    path('fromfile/', views.set_param_fromfile,name = 'unggahparam'),
    path('fromfile/', views.download,name = 'downloadtemp'),

    path('optbeban/',views.create_prm_opt_beban, name= 'prmoptbeban'),
    path('optbeban/list',views.parameteroptbebanlist, name= 'prmoptbebanlist'),
    path('optbeban/<unit>',views.prm_opt_beban_view, name= 'detailpoptbunit'),
    path('optbeban/<unit>/updateoptb',views.update_paramoptb, name= 'updateppoptbunit'),
    path('optbeban/<unit>/deleteoptb',views.delete_parameteroptb, name= 'deletepoptbunit'),


    path('optblending/',views.create_prm_opt_blending, name = 'createprmblending'),
    path('optblending/list',views.parameterblendinglist, name = 'parameterblendinglist'),
    path('optblending/<unit>',views.parameterblending_view, name = 'detailpbunit'),
    path('optblending/<unit>/updatepb',views.parameterblending_update, name = 'updatepbunit'),
    path('optblending/<unit>/deletepb',views.delete_parameterblending, name = 'deletepbunit'),



]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

setparam/views.py
from django.shortcuts import render, get_object_or_404,redirect, HttpResponseRedirect,reverse
from django.contrib import messages
from .models import UnitBoiler, ParameterBlending,ParameterOptPembebanan,RohUnit, HargaPerkiraanBB
from .forms import (UnitBoilerForm, ParameterBlendingForm,UploadParamFromFileForm,
                    ParameterOptPembebananForm, UploadROHFromFileForm, HargaPerkiraanBBForm,)
import os
from django.conf import settings
from django.http import FileResponse, Http404, HttpResponse
from django.core.files.storage import  FileSystemStorage
from . import helper
import decimal
from datetime import date, datetime, timedelta
from django.shortcuts import redirect
import csv,io,datetime, pytz
from django.utils.timezone import get_current_timezone
from django.utils.datastructures import MultiValueDictKeyError
import calendar
from django.db.models import ProtectedError


def roh_csv(request):
    response = HttpResponse(content_type = 'text/csv')
    response['Content-Disposition'] = 'Attachment;filename = rohunit.csv'
    writer = csv.writer(response)
    writer.writerow(['timestamp','roh'])
    #lines =[]
    today = datetime.datetime.today()
    delta = timedelta(minutes=30)
    #dt_format = '%Y-%m-%d %H:%M:%S'
    start = datetime.datetime(today.year, today.month, today.day)
    for i in range(48):
        time = start + (i+1) * delta
        if i == 47:
            time = time - timedelta(minutes=1)
            #time = time.strftime(dt_format)
        #lines.append(time)
        writer.writerow([time])

    return response

def hitung_hpb(hba,kalori,tm,ash,ts):
    k = kalori/6322
    a = (100-tm)/(100-8)
    b = (ts-0.8)* 4
    u = (ash - 15)* 0.4
    return (hba*k*a)-(b+u)

def createHargaPerkiraanBB(request):
    judul = "Form Perkiraan Harga Batubara"
    bulan = datetime.date.today().month
    tahun = datetime.date.today().year
    pesan = None
    hp = HargaPerkiraanBB.objects.filter(bulan=bulan, tahun=tahun).order_by('id').first();
    if not hp:
        pesan = f'Harga patokan bulan {bulan} belum diset'
    else:
        pesan = f'Harga patokan batubara bulan {bulan} sudah diset'
    form = HargaPerkiraanBBForm(request.POST or None)
    context = None

    template = 'setparam/createHPBB.html'
    if request.method =="POST":
        #form = HargaPerkiraanBBForm(request.POST)
        if form.is_valid():
            bulan = form.cleaned_data['bulan']
            tahun = form.cleaned_data['tahun']
            kurs = form.cleaned_data['kursrupiah']
            hba = form.cleaned_data['hbaperton']
            kalori = form.cleaned_data['kalori']
            tm = form.cleaned_data['tm']
            ts = form.cleaned_data['ts']
            ash = form.cleaned_data['ash']
            harga = hitung_hpb(hba, kalori, tm, ash, ts) * kurs / 1000
            hp = HargaPerkiraanBB.objects.create(bulan=form.cleaned_data['bulan'],
                                                               tahun=form.cleaned_data['tahun'],
                                                               hbaperton=hba, kursrupiah=kurs,
                                                               kalori=kalori, tm=tm, ts=ts, ash=ash,
                                                               hargaperkiraan=harga)
            pesan = f'Harga patokan batubara bulan {bulan} sudah diset'

            context ={
                'judul': judul,
                'form': form,
                'hpb': hp,
                'pesan': pesan
            }


    else:
        context={
            'judul': judul,
            'form' : form,
            'hpb': hp,
            'pesan':pesan
        }
    return render(request, 'setparam/createHPBB.html', context)

def editHargaPerkiraanBB(request,id):
    hp = HargaPerkiraanBB.objects.get(id=id)
    form = HargaPerkiraanBBForm(instance=hp)

    if request.method == 'POST':
        form = HargaPerkiraanBBForm(request.POST, instance=hp)
        if form.is_valid():
            form.save()
            return redirect('setparam:createhpbb')
    judul = 'Update Harga Perkiraan Batubara'
    context = {
        'form': form,
        'judul': judul,
    }
    return render(request, 'setparam/createHPBB.html', context)

def deleteHargaPerkiraanBB(request,id):
    hp = HargaPerkiraanBB.objects.get(id=id)
    if request.method == "POST":
        hp.delete()
        return HttpResponseRedirect(reverse('setparam:createhpbb'))
    else:
        context={
            'object':hp,
        }
    return render(request,'setparam/confirm_deletehpb.html', context)




def set_rohunit_fromfile(request):
    context = None
    template = 'setparam/upload_rohunit.html'
    form = UploadROHFromFileForm(None)
    if request.method == "POST":
        form = UploadROHFromFileForm(request.POST,request.FILES)
        if form.is_valid():
            unit = form.cleaned_data['unit']
            csv_file = request.FILES['file']
            if not csv_file.name.endswith('.csv'):
                messages.error(request, 'This is not a csv file')
            dataset = csv_file.read().decode('UTF-8')
            io_string = io.StringIO(dataset)
            next(io_string)
            time2 = None
            for column in csv.reader(io_string, delimiter=',', quotechar="|"):
                dt_format = '%Y-%m-%d %H:%M:%S'
                dt_format2 = 'l, %Y-%m-%d'
                tz = get_current_timezone()
                time = datetime.datetime.strptime(column[0],dt_format)
                time = time.replace(tzinfo= pytz.UTC)
                time2 = time.date()


                #print(f'time:{time}')

                #dt = tz.localize(datetime.datetime.strptime(column[0],dt_format))

                #tz_string = datetime.datetime.now(datetime.timezone.utc).astimezone().tzname()
                #print("datetime.now() :", tz_string)
                _, created = RohUnit.objects.update_or_create(
                        unit=unit,
                        timestamp=time,
                        roh=column[1]
                    )
            rohunit = RohUnit.objects.filter()
            times = time2.strftime('%m/%d/%Y')
            context = {
                'unit': unit,
                'time':times,
                'rohunits': rohunit,
            }
            template = 'setparam/rohunit.html'
            return render(request, template, context)
    else:
        context ={
            'form': form,
        }
    return render(request, template, context)



def download(request):
    #url('/static/images/power.png');
    fs = FileSystemStorage('/media/')
    response = FileResponse(fs.open('settingpembebanan.txt', 'rb'),content_type='text')
    response['Content-Disposition']= 'attachment; filename="settingpembebanan.txt"'
    return response


def set_param_fromfile(request):
    context = None
    data = None
    form = UploadParamFromFileForm(None)
    if request.method == "POST":
        form = UploadParamFromFileForm(request.POST,request.FILES)
        if form.is_valid():
            unit = form.cleaned_data['unit']
            kategori = form.cleaned_data['kategori_param']
            uploadedfile = request.FILES['file']
            #str =[]
            if (kategori=='OPTB'):
                param_value=[]
                for line in uploadedfile:
                    text = line.decode()
                    textsplit = text.split(":")
                    param_value.append(textsplit[1])
                paramoptb= ParameterOptPembebanan.objects.get_or_create(unit = unit, daya_min = int(param_value[0]),
                                                                 daya_max = int(param_value[1]), koef_a_opt_beban = decimal.Decimal(param_value[2]),
                                                                 koef_b_opt_beban = decimal.Decimal(param_value[3]),
                                                                 koef_c_opt_beban = decimal.Decimal(param_value[4]),
                                                                 koef_d_rek_kalor = decimal.Decimal(param_value[5]),
                                                                 koef_e_rek_kalor = decimal.Decimal(param_value[6]),
                                                                 koef_f_rek_kalor = decimal.Decimal(param_value[7]))
                return redirect('setparam:detailpoptbunit',unit=unit.id)
            elif kategori=='BLEND':
                param_value=[]
                for line in uploadedfile:
                     text = line.decode()
                     textsplit = text.split(":")
                     param_value.append(textsplit[1])
                if (len(param_value) == 24):
                    param_blend = ParameterBlending.objects.get_or_create(unit=unit,AH = float(param_value[0]),
                                                                      VM = int(param_value[1]),
                                                                      nku_size = param_value[2],
                                                                      nk_unit = param_value[3],
                                                                      corner1AA = param_value[4],corner2AA = param_value[5],corner3AA = param_value[6],corner4AA = param_value[7],
                                                                      corner1AB=param_value[8],corner2AB = param_value[9],corner3AB = param_value[10],corner4AB = param_value[11],
                                                                      corner1CD=param_value[12],corner2CD = param_value[13],corner3CD = param_value[14],corner4CD = param_value[15],
                                                                      corner1EF=param_value[16],corner2EF = param_value[17],corner3EF = param_value[18],corner4EF = param_value[19],
                                                                      corner1FF=param_value[20], corner2FF=param_value[21],corner3FF=param_value[22], corner4FF=param_value[23])

setparam/templates/setparam/confirm_deletehpb.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h3><p> Are you sure you want to delete harga perkiraan batubara: {{object.bulan}} - {{object.tahun}} ?"</p></h3>

    <form method="POST" action="{% url 'setparam:deletehpbb' object.id %}">
        {% csrf_token %}


        <input type="submit" value="Confirm" class="btn btn-warning">
        <a href= "{% url 'setparam:createhpbb' %}" class="btn btn-default"> Cancel </a>
    </form>

{% endblock content %}

setparam/templates/setparam/confirm_deleteoptb.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h3><p> Are you sure you want to delete param optimasi pembebanan: {{object.unit}} ?"</p></h3>

    <form method="POST" action="{% url 'setparam:deletepoptbunit' object.unit.id %}">
        {% csrf_token %}


        <input type="submit" value="Confirm" class="btn btn-warning">
        <a href= "{% url 'setparam:prmoptbebanlist' %}" class="btn btn-default"> Cancel </a>
    </form>

{% endblock content %}

setparam/templates/setparam/confirm_deleteub.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h3><p> Are you sure you want to delete blending param: {{object.unit}} ?"</p></h3>

    <form method="POST" action="{% url 'setparam:deletepbunit' object.unit.id %}">
        {% csrf_token %}


        <input type="submit" value="Confirm" class="btn btn-warning">
        <a href= "{% url 'setparam:parameterblendinglist' %}" class="btn btn-default"> Cancel </a>
    </form>

{% endblock content %}

setparam/templates/setparam/createHPBB.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="alert alert-primary" role="alert">
    <h3>{{ judul }}</h3>
</div>
<form method="POST">
    {% csrf_token %}

    {% for data in form %}
    <div class="form-group">
        <label class="col-sm-2 col-form-label">{{data.label_tag}}</label>
        <div class="col-sm-12">
            {{data}}
        </div>
    </div>
    {% endfor %}
    <br>
    <button type="submit" class="btn btn-primary ">Simpan</button>
    <a class="btn btn-secondary" href="{% url 'setparam:createhpbb' %}">Cancel</a>
</form>

<div class="row g-3">
    <p></p>
</div>
<div class="alert alert-primary" role="alert">
    <h3>{{ pesan }}</h3>
</div>
<div class="alert alert-primary" role="alert">
    <h3>Harga Patokan Batubara</h3>
</div>
<table class="table table-striped">
    <thead>
    <tr>

        <th scope="col">Bulan</th>
        <th scope="col">Tahun</th>
        <th scope="col">Harga Perkiraan (Rp/kg)</th>
        <th scope="col">Harga Acuan ($/ton)</th>
        <th scope="col">Kalori</th>
        <th scope="col">TM</th>
        <th scope="col">TS</th>
        <th scope="col">ASH</th>
    </tr>
    </thead>
    <tbody>
    {% if hpb %}
    <tr>
        <td>{{ hpb.bulan }}</td>
        <td>{{ hpb.tahun }}</td>
        <td>{{ hpb.hargaperkiraan |floatformat:-2 }}</td>
        <td>{{ hpb.hbaperton }}</td>
        <td>{{ hpb.kalori }}</td>
        <td>{{ hpb.tm}}</td>
        <td>{{ hpb.ts }}</td>
        <td>{{ hpb.ash }}</td>
        <td>
            <form method="post" action="#">
                {% csrf_token %}
                <a href="{% url 'setparam:edithpbb' hpb.id %}" class="btn btn-outline-success">Edit</a>
                <a href="{% url 'setparam:deletehpbb' hpb.id %}" class="btn btn-outline-warning">Delete</a>
            </form>
        </td>
    </tr>
    {% endif %}


    </tbody>
</table>

{% endblock %}

setparam/templates/setparam/index.html
{% extends "base.html" %}

{% block title %}
    {{heading}}
{% endblock title %}

{% block content %}
     <div class="alert alert-primary" role="alert">
            <h3>Tambahkan Setting Unit Boiler Untuk Optimasi Blending</h3>
        </div>
    <form method="POST">
        {% csrf_token %}

        {% for data in data_form %}
            <div class="form-group">
                <label class="col-sm-2 col-form-label">{{data.label_tag}}</label>
                <div class="col-sm-12">
                     {{data}}
                </div>
            </div>
        {% endfor %}
        <br>
         <button type="submit" class="btn btn-primary btn-lg btn-block">Simpan</button>
    </form>

{% endblock content %}

setparam/templates/setparam/parameterblendingview.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-sm">
            <h3 class="p-3 mb-2 bg-primary text-white"> Setting Parameter Optimasi Blending  {{parameterblending.unit}} </h3>
        </div>
      </div>



    <div class="row">
            <div class="col-3">
              <div class="p-3 mb-2 bg-light text-dark">
                <h5> Unit</h5>
              </div>
            </div>
            <div class="col">
              <div class="p-3 mb-2 bg-light text-dark">
                <h5>: {{parameterblending.unit}}</h5>
              </div>
            </div>

    </div>

    <div class="row">
            <div class="col-3">
              <div class="p-3 mb-2 bg-light text-dark">
                <h5> AH </h5>
              </div>
            </div>
            <div class="col">
              <div class="p-3 mb-2 bg-light text-dark">
                <h5>: {{parameterblending.AH}}</h5>
              </div>
            </div>
            <div class="col-2">
              <div class="p-3 mb-2 bg-light text-dark">
                <h5> VM </h5>
              </div>
            </div>
            <div class="col">
              <div class="p-3 mb-2 bg-light text-dark">
                <h5>: {{parameterblending.VM}}</h5>
              </div>
            </div>

    </div>

     <div class="row">
            <div class="col-3">
              <div class="p-3 mb-2 bg-light text-dark">
                <h5> Jumlah parameter kalor unit </h5>
              </div>
            </div>
            <div class="col">
              <div class="p-3 mb-2 bg-light text-dark">
                <h5>: {{parameterblending.nku_size}}</h5>
              </div>
            </div>
            <div class="col-2">
              <div class="p-3 mb-2 bg-light text-dark">
                <h5> Kalor Unit </h5>
              </div>
            </div>
            <div class="col">
              <div class="p-3 mb-2 bg-light text-dark">
                <h5>: {{parameterblending.nk_unit}}</h5>
              </div>
            </div>

    </div>
    <div class="row">
        <div class="col">
            <div class="p-3 mb-2 bg-light text-dark">
                <h5>Koefisien Corner Pada Setiap Layer</h5>
            </div>
        </div>

    </div>

        <div class="row">
                <div class="col">
                  <div class="p-3 mb-2 bg-light text-dark">
                    <ul class="list-group">
                      <li class="list-group-item active">Layer AA</li>
                      <li class="list-group-item">Corner 1: {{parameterblending.corner1AA}}</li>
                      <li class="list-group-item">Corner 2: {{parameterblending.corner2AA}}</li>
                      <li class="list-group-item">Corner 3: {{parameterblending.corner3AA}}</li>
                      <li class="list-group-item">Corner 4: {{parameterblending.corner4AA}}</li>
                    </ul>
                  </div>
                </div>
                <div class="col">
                  <div class="p-3 mb-2 bg-light text-dark">
                    <ul class="list-group">
                      <li class="list-group-item active">Layer AB</li>
                      <li class="list-group-item">Corner 1: {{parameterblending.corner1AB}}</li>
                      <li class="list-group-item">Corner 2: {{parameterblending.corner2AB}}</li>
                      <li class="list-group-item">Corner 3: {{parameterblending.corner3AB}}</li>
                      <li class="list-group-item">Corner 4: {{parameterblending.corner4AB}}</li>
                    </ul>
                  </div>
                </div>
                <div class="col">
                  <div class="p-3 mb-2 bg-light text-dark">
                    <ul class="list-group">
                      <li class="list-group-item active">Layer CD</li>
                      <li class="list-group-item">Corner 1: {{parameterblending.corner1CD}}</li>
                      <li class="list-group-item">Corner 2: {{parameterblending.corner2CD}}</li>
                      <li class="list-group-item">Corner 3: {{parameterblending.corner3CD}}</li>
                      <li class="list-group-item">Corner 4: {{parameterblending.corner4CD}}</li>
                    </ul>
                  </div>
                </div>

    </div>


        <div class="row">
                <div class="col">
                  <div class="p-3 mb-2 bg-light text-dark">
                    <ul class="list-group">
                      <li class="list-group-item active">Layer EF</li>
                      <li class="list-group-item">Corner 1: {{parameterblending.corner1EF}}</li>
                      <li class="list-group-item">Corner 2: {{parameterblending.corner2EF}}</li>
                      <li class="list-group-item">Corner 3: {{parameterblending.corner3EF}}</li>
                      <li class="list-group-item">Corner4: {{parameterblending.corner4EF}}</li>
                    </ul>
                  </div>
                </div>
                <div class="col">
                  <div class="p-3 mb-2 bg-light text-dark">
                    <ul class="list-group">
                      <li class="list-group-item active">Layer FF</li>
                      <li class="list-group-item">Corner 1: {{parameterblending.corner1FF}}</li>
                      <li class="list-group-item">Corner 2: {{parameterblending.corner2FF}}</li>
                      <li class="list-group-item">Corner 3: {{parameterblending.corner3FF}}</li>
                      <li class="list-group-item">Corner 4: {{parameterblending.corner4FF}}</li>
                    </ul>
                  </div>
                </div>
                <div class="col">
                  <div class="p-3 mb-2 bg-light text-dark">

                  </div>
                </div>

    </div>





{% endblock content %}

setparam/templates/setparam/rohunit.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{heading}}
{% endblock title %}

{% block content %}

       <div class="alert alert-primary" role="alert">
            <h3>Daftar ROH {{unit}} ({{time}})</h3>
        </div>
        <table class="table table-striped">
          <thead>
            <tr>


              <th scope="col">Time</th>
                <th scope="col">ROH</th>
            </tr>
          </thead>
          <tbody>
            {% for rohunit in rohunits %}
            <tr>
                <td>{{ rohunit.timestamp|date:'Y-m-d G:i:s'}}</td>
                <td>{{ rohunit.roh}}</td>
              <td>

                  <form method="post" action="#">
                      {% csrf_token %}
                      <a href="#" class="btn btn-outline-success">Edit</a>
                     <a href="#"  class="btn btn-outline-warning">Delete</a>


                  </form>



              </td>


            </tr>
            {% endfor %}
          </tbody>
        </table>

{% endblock content %}

setparam/templates/setparam/setparamfromfile.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{heading}}
{% endblock title %}

{% block content %}
     <div class="alert alert-primary" role="alert">
            <h3>Tambahkan Setting Unit Boiler </h3>
        </div>
    <form method="post" >
        {% csrf_token %}
        <ul class="list-group">
          <li class="list-group-item active" aria-current="true">Unduh Template File</li>
          <li class="list-group-item">
               <a href="{% static 'media/settingpembebanan.txt'%}" download>Unduh Template Setting Parameter Optimasi Pembebanan</a>
          </li>
          <li class="list-group-item">
              <a href="{% static 'media/settingblending.txt'%}" download>Unduh Template Setting Parameter Blending</a>
          </li>
        </ul>


    </form>



    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {% for data in form %}
            <div class="form-group">
                <label class="col-sm-2 col-form-label">{{data.label_tag}}</label>
                <div class="col-sm-12">
                     {{data}}
                </div>
            </div>
        {% endfor %}
        <br>
         <button type="submit" class="btn btn-primary btn-lg btn-block">Upload</button>
    </form>

        <p>{{ data }}</p>

{% endblock content %}

setparam/templates/setparam/unitform.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<div class="alert alert-primary" role="alert">
    <h3>{{ judul }} {{ form.}}</h3>
</div>
<form method="POST">
    {% csrf_token %}

    {% for data in form %}
    <div class="form-group">
        <label class="col-sm-2 col-form-label">{{data.label_tag}}</label>
        <div class="col-sm-12">
            {{data}}
        </div>
    </div>
    {% endfor %}
    <br>
    {% if edited %}
    <button type="submit" class="btn btn-primary ">Simpan</button>
    {% endif %}
    <a class="btn btn-secondary" href="{% url 'setparam:createub' %}">Cancel</a>
</form>
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

{% if error %}
      <div class="alert alert-danger">
            <strong>{{ pesan|escape }}</strong>
        </div>
{% endif %}
<div class="row g-3">
    <p></p>
</div>
<div class="alert alert-primary" role="alert">
    <h3>Daftar Unit Boiler</h3>
</div>
<table class="table table-striped">
    <thead>
    <tr>

        <th scope="col">Nama PLTU</th>
        <th scope="col">Nama Unit</th>
        <th scope="col">Tindakan</th>
    </tr>
    </thead>
    <tbody>
    {% for unit in units %}
    <tr>
        <td>{{ unit.namapltu }}</td>
        <td>{{ unit.namaunit }}</td>

        <td>

            <form method="post" action="#">
                {% csrf_token %}
                <a href="{% url 'setparam:viewunit' unit.id %}" class="btn btn-outline-success">View</a>
                <a href="{% url 'setparam:updateunit' unit.id %}" class="btn btn-outline-success">Edit</a>
                <a href="{% url 'setparam:deleteunit' unit.id %}" class="btn btn-outline-warning">Delete</a>


            </form>


        </td>


    </tr>
    {% endfor %}
    </tbody>
</table>


{% endblock %}

setparam/templates/setparam/upload_rohunit.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{heading}}
{% endblock title %}

{% block content %}
     <div class="alert alert-primary" role="alert">
            <h3>Tambahkan Setting ROH Unit Boiler </h3>
        </div>
    <form method="post" >
        {% csrf_token %}
        <ul class="list-group">
          <li class="list-group-item active" aria-current="true">Unduh Template File</li>
          <li class="list-group-item">
               <a href="{% url 'setparam:rohtemplate' %}" download>Unduh Template Setting ROH</a>
          </li>

        </ul>


    </form>



    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {% for data in form %}
            <div class="form-group">
                <label class="col-sm-2 col-form-label">{{data.label_tag}}</label>
                <div class="col-sm-12">
                     {{data}}
                </div>
            </div>
        {% endfor %}
        <br>
         <button type="submit" class="btn btn-primary btn-lg btn-block">Upload</button>
    </form>

       <div class="alert alert-primary" role="alert">
            <h3>Daftar ROH Unit </h3>
        </div>
        <table class="table table-striped">
          <thead>
            <tr>

              <th scope="col">Nama PLTU</th>
              <th scope="col">Nama Unit</th>
              <th scope="col">Time</th>
                <th scope="col">ROH</th>
            </tr>
          </thead>
          <tbody>
            {% for rohunit in rohunits %}
            <tr>
              <td>{{ rohunit.unit.namapltu }}</td>
              <td>{{ rohunit.unit.namaunit }}</td>
                <td>{{ rohunit.timestamp|date:'Y-m-d G:i:s'}}</td>
                <td>{{ rohunit.roh}}</td>
              <td>

                  <form method="post" action="#">
                      {% csrf_token %}
                      <a href="#" class="btn btn-outline-success">Edit</a>
                     <a href="#"  class="btn btn-outline-warning">Delete</a>


                  </form>



              </td>


            </tr>
            {% endfor %}
          </tbody>
        </table>

{% endblock content %}