blending/urls.py
from django.urls import path
from  . import views

urlpatterns =[
    path('coalstock/',views.coalspec_list, name = 'coalstockforblending'),
    path('blending/',views.calculate_blending, name = 'calculateblending'),
    path('blending/history',views.search_history, name= 'searchhistory'),
    path('blending/resumehistory',views.search_resume_history, name= 'searchresumehistory'),
    path('note/',views.create_note, name = 'createnote'),

    path('blending/prep',views.prepare_for_blend, name = 'prepareblending'),


]

coaljson/urls.py
from django.urls import path
from  . import views
from .views import SelectCoalView
from django.contrib.auth import views as authview
from .forms import UserLoginForm
urlpatterns =[
    path('coal/',views.new_coal, name='new_coal'),
    path('coaljson/',views.new_coal_json, name='new_coal_json'),
    path('coalspec/', views.new_coal_spec,name='coalspeccreate'),
    path('coalspeclist/',views.coalspec_list, name='coalspeclist'),
    path('coalspeclistapi/', views.coalspecserializer_list, name ='coalspecapi'),
    # path('',authview.LoginView.as_view(
    #         template_name="login.html",
    #         authentication_form=UserLoginForm
    #         ),
    #     name='login'),

    path('',views.index, name = 'index'),
    path('coalstock/', views.new_coal_stock_unit, name='new_coal_stock'),
    path('coalstock/<unit>/listcsu', views.coal_stock_unit_list, name='coal_stock_unit_list'),
    path('coalstock/search', views.search_stock_unit, name='search_coal_stock_unit'),
    path('coalstock/search_old', views.search_stock_unit_old, name='search_coal_stock_unit_old'),
    path('coalstock/search_op', views.search_stock_unit_short, name='search_coal_stock_unit_short'),

    path('coalstock/<id>/updateunit', views.update_coal_stock_unit, name='updatecoalstock'),
    path('coalstock/<id>/updatesimple', views.update_stock_simple, name='simpleupdatecoal'),
    path('coalstock/<id>/update', views.update_stock_simple2, name='simpleupdatecoal2'),
    path('coalstock/delete/<id>', views.delete_coal_stock_unit, name='deletecoalstock'),
    path('coalstock/fromapi', views.coalstockfromapi, name='getcoalstockfromapi'),
    #path('coalstock/prep/', views.get_coal_for_blending, name='preparecoalforblending'),
    path('coalstock/prep/', views.get_coal_for_blending_op, name='preparecoalforblending'),
    path('coalstock/<unit>/list', views.view_coal_stock_unit, name='coal_stock_unit'),
    path('coalstock/temp/', views.generatebiofromtemp, name='generate_bio_from_temp'),

    path('coalstock/fromspecapi', views.get_coal_from_db, name='getcoalstockfromspecapi'),

    path('coalstock/bio', views.get_bio_for_blending, name='getbioforblend'),
    path('coalstock/bio/<int:bio_id>', views.select_bio_for_blending, name='selectbioforblend'),
    path('coalstock/tkg', views.get_coal_tk_for_blending, name='gettongkang'),
    path('coalstock/tk/<int:coaltk_id>', views.select_coal_tk_for_blending, name='selecttongkang'),
    path('coalstock/cyd', views.get_coal_cyrd_for_blending, name='getcoalyard'),
    path('coalstock/cyd/<int:cyrd_id>', views.get_coal_cyrd_for_blending, name='selectcoalyards'),
    path('coalstock/next', views.nextstep_setunit, name='nextstepsetunit'),
    path('coalstock/cyd/<int:cyrd_id>', views.submit_coal_for_blending, name='submitcoalforblend'),
    path('coalstock/select/<int:pk>', SelectCoalView.as_view(), name="selectcoal")








]

optpembebanan/urls.py
from django.urls import path
from  . import views

urlpatterns =[

    #path('calculateoptb/',views.calc_optimasi_beban, name = 'calculateoptb'),
    path('calculateoptb/select',views.select_unit_optb, name = 'selectunitoptb'),
    path('calculateoptb/rk',views.calculate_rk_unit_update, name = 'calculate_rku'),
    path('calculateoptb/view_rk',views.view_rk_unit, name = 'view_rku'),
    path('calculateoptb/roh',views.unggah_roh_unit_harian, name = 'unggah_roh'),

]

restfulapicrud/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('setparam/', include(('setparam.urls', 'setparam'), namespace='setparam')),
    path('blending/', include(('blending.urls', 'blending'), namespace='blending')),
    path('optbeban/', include(('optpembebanan.urls', 'optbeban'), namespace='optbeban')),
    path('',include(('coaljson.urls','coaljson'),namespace='coaljson')),
    #path('',include('crudbasic.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),


]

setparam/urls.py
from django.urls import path
from  . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns =[

    path ('ub/',views.create_ub,name ='createub'),
    path ('ub/<id>/view',views.view_unitboiler, name ='viewunit'),
    path ('ub/list',views.list_ub,name ='listunitboiler'),
    path('ub/<id>/updateub',views.update_unitboiler, name = 'updateunit'),
    path('ub/<id>/deleteub',views.delete_unitboiler, name = 'deleteunit'),

    path('roh/',views.set_rohunit_fromfile, name = 'setroh'),
    path('roh/template',views.roh_csv, name = 'rohtemplate'),

    path('hpbb/', views.createHargaPerkiraanBB, name ='createhpbb'),
    path('hpbb/<id>/deletehp', views.deleteHargaPerkiraanBB, name ='deletehpbb'),
    path('hpbb/<id>/edithp', views.editHargaPerkiraanBB, name ='edithpbb'),

    path('fromfile/', views.set_param_fromfile,name = 'unggahparam'),
    path('fromfile/', views.download,name = 'downloadtemp'),

    path('optbeban/',views.create_prm_opt_beban, name= 'prmoptbeban'),
    path('optbeban/list',views.parameteroptbebanlist, name= 'prmoptbebanlist'),
    path('optbeban/<unit>',views.prm_opt_beban_view, name= 'detailpoptbunit'),
    path('optbeban/<unit>/updateoptb',views.update_paramoptb, name= 'updateppoptbunit'),
    path('optbeban/<unit>/deleteoptb',views.delete_parameteroptb, name= 'deletepoptbunit'),


    path('optblending/',views.create_prm_opt_blending, name = 'createprmblending'),
    path('optblending/list',views.parameterblendinglist, name = 'parameterblendinglist'),
    path('optblending/<unit>',views.parameterblending_view, name = 'detailpbunit'),
    path('optblending/<unit>/updatepb',views.parameterblending_update, name = 'updatepbunit'),
    path('optblending/<unit>/deletepb',views.delete_parameterblending, name = 'deletepbunit'),



]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>
        {% block title %}

        {% endblock title %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">


    <style>
.navbar-nav .nav-item.active .nav-link,
.navbar-nav .nav-item:hover .nav-link {
    background-color: grey;
    color:white;
}

.container {
    width: 80%;
    margin-top:80px;
    padding: 15px;
    background-size:100% auto;
    position:relative;
    margin-bottom:80px;

}
.box {
    width: 55%;
    margin-top:10px;
    box-shadow: 0 3px 10px rgba(0,0,0,0.4);
    padding: 15px;
    background-size:100% auto;
    position:relative;
    border-radius:15px;
    border:none;
   box-sizing:content-box;
   left:25%;

}

.card {
   margin-top:10%;
   width:100%;
   padding:25px;
   border:none;

}

.footer{
    width: 100%;
    height: 50px;
    padding-left: 10px;
    line-height: 50px;
    background: #aaa;
    color: #fff;
    color:black;
    text-align:center;
}


    </style>



</head>
<body>

<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#" style="margin-left:200px;">
            <img src="../../static/images/logoip.png" alt="" width="120" height="40"
                 class="d-inline-block align-text-top">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">


                {% if user.is_authenticated %}
                {% if user.is_superuser%}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink5" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Admin
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'admin:index'  %}">Kelola User</a></li>


                    </ul>
                    {% endif %}
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Unit Boiler
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'setparam:createub' %}">Daftar Unit Boiler</a></li>
                       <!-- <li><a class="dropdown-item" href="{% url 'setparam:setroh' %}">Set ROH Unit Boiler</a></li> !-->
                        <li><a class="dropdown-item" href="{% url 'setparam:createhpbb' %}">Set Harga Perkiraan
                            Batubara</a></li>
                        <li><a class="dropdown-item" href="{% url 'setparam:unggahparam' %}">Set Parameter Optimasi dari
                            File</a></li>
                        <li><a class="dropdown-item" href="{% url 'setparam:prmoptbeban' %}">Set Parameter Optimasi
                            Pembebanan</a></li>
                        <li><a class="dropdown-item" href="{% url 'setparam:createprmblending' %}">Set Parameter
                            Optimasi Blending</a></li>
                        <li><a class="dropdown-item" href="{% url 'setparam:prmoptbebanlist'%}">Daftar Parameter
                            Optimasi Pembebanan</a></li>
                        <li><a class="dropdown-item" href="{% url 'setparam:parameterblendinglist'%}">Daftar Parameter
                            Optimasi Blending</a></li>

                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink2" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Rencana Operasional Harian (ROH)
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'optbeban:unggah_roh' %}">Unggah ROH</a></li>
                      <!--  <li><a class="dropdown-item" href="{% url 'optbeban:selectunitoptb' %}">Hitung Beban Unit</a> </li> -->
                        <!--<li><a class="dropdown-item" href="{% url 'optbeban:calculate_rku' %}">Hitung Rekomendasi Kalor Harian</a></li>!-->
                        <li><a class="dropdown-item" href="{% url 'optbeban:view_rku' %}">Cek Rekomendasi Operasional Harian</a></li>

                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink1" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Stok Bahanbakar
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <!--<li><a class="dropdown-item" href="{% url 'coaljson:getcoalstockfromspecapi' %}">Get Coal Stock From API</a></li>-->
                         <li><a class="dropdown-item" href="{% url 'coaljson:getbioforblend' %}">Penyiapan bahanbakar untuk bending </a></li>
                        <!--<li><a class="dropdown-item" href="{% url 'coaljson:preparecoalforblending' %}">Penyiapan data bahanbakar untuk bending </a></li> -->

                        <!-- <li><a class="dropdown-item" href="{% url 'coaljson:getcoalstockfromapi' %}">Siapkan Coal dan Biomassa </a></li> -->
                        <li><a class="dropdown-item" href="{% url 'coaljson:search_coal_stock_unit_short' %}">Lihat stok hari ini </a></li>
                        <li><a class="dropdown-item" href="{% url 'coaljson:search_coal_stock_unit' %}">Lihat stok hari ini (detail)</a></li>
                         <!--<li><a class="dropdown-item" href="{% url 'coaljson:search_coal_stock_unit_old' %}">Lihat Stok lampau (detail)</a></li>-->

                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink3" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Blending
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'blending:prepareblending' %}">Prepare Blanding</a></li>
                        <li><a class="dropdown-item" href="{% url 'blending:calculateblending' %}">Blending</a></li>
                        <li><a class="dropdown-item" href="{% url 'blending:searchresumehistory' %}">Arsip Blending
                            (Resume)</a></li>

                        <li><a class="dropdown-item" href="{% url 'blending:searchhistory' %}">Arsip Blending</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink4" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.get_username }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="userMenu">
                        <li><a class="nav-link" href="{% url 'blending:createnote' %}">Create Note</a></li>
                        <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>

                    </ul>
                </li>


                {% endif %}
            </ul>
        </div>
          <a class="navbar-brand" href="#" style="margin-right:200px;">
            <img src="../../static/images/logo_n.png" alt="" width="160" height="50"
                 class="d-inline-block align-text-top">
        </a>
    </div>
</nav>


<div class="container">
    {% block content %}

    {% endblock content %}
</div>


<!--    Footer -->


<footer class="footer fixed-bottom">
    <div style="font-color:black; text-center">
        <p class="copyright-text">Copyright &copy; 2021 All Rights Reserved by
            <a href="#">Teknik Informatika Universitas Trisakti</a>
        </p>
    </div>
</footer>



<!--<script src="{% static 'js/jquery.js' %}"></script>-->
<!--<script src="{% static 'js/bootstrap.min.js' %}"></script>-->
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"> </script>
<script src='https://code.jquery.com/jquery-3.2.1.min.js'> </script>
<script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
 {% block script %}
 {% endblock script%}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}
{{heading}}
{% endblock title %}

{% block content %}

{% if user.is_authenticated %}
<div class="box">
    <div class="row">
        <div class="col-4 " style=" padding:0px; margin-top:0px;">
            <img src="../../static/images/nemesys.png" max-widht="100%" height=auto" alt="" class="img-fluid rounded" style="margin-left:10px;">
        </div>

        <div class="col-8">
            <div class="card">
                <h5 class="" style="margin-top:20px" > Welcome to Nemesys Web </h5>
				<h4>Hello {{user.username}} </h4>
                <hr>
{% else %}
<div class="box">
    <div class="row">
        <div class="col-6 " style="padding:0px; margin-top:0px;">
            <img src="../../static/images/newpict.png" max-widht="100%" height=auto" alt="" class="img-fluid rounded">
        </div>

        <div class="col-6">
            <div class="card">
                <h5 class="" style="margin-top:20px"> Sign into your account </h5>
                <hr>
                <form method="post" action="{% url 'login' %}">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="{{ form.username.id_for_label }}">Email</label>
                        <input type="email" name="username" class="form-control"
                               placeholder="Masukkan Email Anda">
                    </div>


                    <div class="form-group">
                        <label for="{{ form.password.id_for_label }}">Password</label>
                        <input type="password" name="password" class="form-control"
                               placeholder="Masukkan Password Anda">
                    </div>


                    <br>
                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary">LOGIN</button>
                    </div>


                </form>
            </div>
        </div>

    </div>
</div>


{% endif %}
{% endblock content %}

templates/login.html
{% extends 'base.html' %}

{% block title %} Indonesia Power Project {% endblock %}
{% load static %}


<style>
	*{
		padding: 0;
		margin: 0;
		box-sizing: border-box;
	}
	body{
		background: (219, 226, 226);
	}
	.row{
		background: #ffff;
		border-radius: 30px;
		box-shadow: 7px 10px 10px grey;
	}
	img{
		border-top-left-radius: 30px;
		border-bottom-left-radius: 30px;
	}
	.btn1{
		border: none;
		outline: none;
		height: 50px;
		width: 100%;
		background-color: 	#0000ff;
		color: #ffff;
		border-radius: 4px;
		font-weight: bold;
	}
	.btn1:hover{
		background: #ffff;
		border: 1px solid;
		color: #0000ff;
	}
</style>


 {% block content %}
 <section class="form my-5 mx-6">
	  	<div class="container">
	  		<div class="row no-gutters">
	  			<div class="col-lg-5">
	  					<img src="{% static 'images/newpict.png' %}" class="img-fluid" alt="">
	  			</div>
	  			<div class="col-lg-7 px-5 pt-5">
	  				<h4> Sign into your account</h4>

					<form method="post" action="#">
						{% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">

        <label for="{{ form.username.id_for_label }}">Username:</label>
        {{ form.username }}
        {{ form.username.errors }}

    </div>
    <div class="form-group">

        <label for="{{ form.password.id_for_label }}">Password:</label>
        {{ form.password }}
        {{ form.password.errors }}
    </div>
    <button type="submit">Login</button>
</form>

	  		</div>
	  	</div>
  </section>
 </section


{% endblock %}

templates/login1.html
{% extends 'base.html' %}

{% block title %} Indonesia Power Project {% endblock %}
{% load static %}

 {% block content %}
<div class="container-fluid ps-md-0">
  <div class="row g-0">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
            <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
              <h3 class="login-heading mb-4">Welcome back!</h3>

              <!-- Sign In Form -->
              <form>
                <div class="form-floating mb-3">
                  <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                  <label for="floatingInput">Email address</label>
                </div>
                <div class="form-floating mb-3">
                  <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
                  <label for="floatingPassword">Password</label>
                </div>



                <div class="d-grid">
                  <button class="btn btn-lg btn-primary btn-login text-uppercase fw-bold mb-2" type="submit">Sign in</button>

                </div>

              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock content %}